### ISSUE TITLE
Docs show two resource libraries

### ISSUE THREAD

**Issue by sethladd** [dart-lang/resource#10]
https://www.dartdocs.org/documentation/resource/1.1.0/index.html

![screen shot 2016-01-27 at 7 58 56 am](https://cloud.githubusercontent.com/assets/5479/12619184/dc7a0ab8-c4cb-11e5-83ce-32214063323f.png)

**Comment by lrhn** [comment]
Tricky! One is actually `browser_resource.dart`, but it is supposed to be a plug-in replacement so it has the same name.

Maybe not that great an idea in the end :)

**Comment by sethladd** [comment]
Using library names that match the import name would work. That makes it more obvious how to import, too.

**Comment by kevmoo** [comment]
Fix out for review: https://codereview.chromium.org/1657173004/

**Comment by sethladd** [comment]
Still showing two resource libraries: https://www.dartdocs.org/documentation/resource/1.1.0/index.html

**Comment by sethladd** [comment]
Oh, I see it's for 1.1-dev. Will open a new issue to publish 1.1 :)
