### ISSUE TITLE
Please add tags corresponding to published versions on pub

### ISSUE THREAD

**Issue by whesse** [dart-lang/resource#14]
There are versions of this package published on pub, but no corresponding tags (releases) in this repo.
Please fix.

**Comment by whesse** [comment]
And publish a new version, if you want us to roll it in the sdk/DEPS.

**Comment by lrhn** [comment]
Released new version, added release tag for it.
Do we need to find the tags for earlier versions?

**Comment by whesse** [comment]
Not for my sake, but it would be good to do.
