### ISSUE TITLE
Missing import in io_io.dart 

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/resource#18]
In io_io.dart, the `_throwIfFailed` method is referencing `HttpException`, but that class is hidden by the import, resulting in a Class Not Found exception thrown whenever `_throwIfFailed` gets invoked. 

Fix: add `HttpException` to the import statement in io_io.dart, Line 12, like so:

```
import "dart:io" show File,
                      HttpStatus,
                      HttpClient,
                      HttpClientResponse,
                      HttpClientRequest,
                      HttpHeaders,
                      HttpException;
```

Thanks

**Comment by lrhn** [comment]
Done
