### ISSUE TITLE
Resource loading failing the 224th time

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/resource#19]
So I am doing a project generator similar to [stagehand](https://github.com/google/stagehand).
I am using it via `pub global`.

When looping over file references in order to copy their contents into a target directory, I am always getting an `HttpException: Not Found` upon reaching the 224th file, with all successive attempts reporting a closed connection (`HttpException: Connection closed before full header was received`). I excluded and shuffled files around, no matter the file name or type, the loop always exits on the 224th file. 

Is that a magic number or some timeout coincidence, and, more importantly, how would I prevent this from happening? Thanks!

Code:
```dart
  Resource myResource;
  for (int i = 0; i < data.length; i += 3) {
    String path = data[i];
    String type = data[i + 1];

   //quick hack to exclude some files from iteration. It always ends at the 224nd file. 
   if(path.endsWith(".png")){
     // continue;
    }

    myResource = new Resource('package:rockdot_generator/templates/${pack}/${path}');

    print("${counter++} - decoding: $path");

    if (type == 'binary') {

      try{
        List<int> bytes = await myResource.readAsBytes();
        TemplateFile templateFile = new TemplateFile.fromBinary(path, bytes);
        results.add(templateFile);
      }
      catch(e){
        print("error: $e, path: $path");
      }
    } else {

      try{
        String source = await myResource.readAsString();
        results.add(new TemplateFile(path, source));
      }
      catch(e){
        print("error: $e, path: $path");
      }
    
    }
  }
```

Trace:
```
...
222 - decoding: lib/examples/spine/assets/spineboy-mesh/spineboy-mesh.png
223 - decoding: lib/examples/spine/assets/stretchyman/stretchyman.atlas
error: HttpException: Not Found, uri = http://localhost:64117/packages/rockdot_generator/templates/master/lib/examples/spine/assets/stretchyman/stretchyman.atlas, path: lib/examples/spine/assets/stretchyman/stretchyman.atlas
224 - decoding: lib/examples/spine/assets/stretchyman/stretchyman.png
error: HttpException: Connection closed before full header was received, uri = http://localhost:64117/packages/rockdot_generator/templates/master/lib/examples/spine/assets/stretchyman/stretchyman.png, path: lib/examples/spine/assets/stretchyman/stretchyman.png
225 - decoding: lib/examples/spine/assets/tank/tank.atlas
error: HttpException: Connection closed before full header was received, uri = http://localhost:64117/packages/rockdot_generator/templates/master/lib/examples/spine/assets/tank/tank.atlas, path: lib/examples/spine/assets/tank/tank.atlas
...
```

**Comment by lrhn** [comment]
Only going by the symptoms, it seems like the server dies at the 224th file.
It doesn't find the file (even if it's there), and then goes into a bad state where it won't accept further requests.
That sounds conspicuously like your process is running out of file descriptors, so something is likely leaking them. 

You are getting your `package:`-URI resources from an HTTP server. Is this the pub server (`pub serve`)?
What operating system are you running on? On Unixes or OS-X you can use `lsof -i -P -n` to list the open network connections or `lsof -p processID` to see the open connections of a specific process.  It might give a clue to which ports or files are staying open (probably something repeated 223 times).

**Comment by nilsdoehring** [comment]
Thank you for the direction!

I'm on OSX 10.11.6 (El Capitan), with Dart SDK 1.21.1.
My package is activated via `pub global`, and I access via `pub global run ...`, so I guess there is some `pub serve`going on, internally.

First, I did look at the network connections, and there's a lot open in parallel (223 in total, I guess), indeed, in more than one dart process. Snippet:
```
...
dart      98547 jdoe  251u  IPv6 0xbe89e64bb62af0ff      0t0  TCP [::1]:53856->[::1]:54090 (ESTABLISHED)
dart      98547 jdoe  252u  IPv6 0xbe89e64bb630c09f      0t0  TCP [::1]:53856->[::1]:54091 (ESTABLISHED)
dart      98547 jdoe  253u  IPv6 0xbe89e64bb630bb3f      0t0  TCP [::1]:53856->[::1]:54093 (ESTABLISHED)
dart      98547 jdoe  254u  IPv6 0xbe89e64bb630d0bf      0t0  TCP [::1]:53856->[::1]:54094 (ESTABLISHED)
dart      98547 jdoe  255u  IPv6 0xbe89e64bb630db7f      0t0  TCP [::1]:53856->[::1]:54095 (ESTABLISHED)
dart      98568 jdoe   10u  IPv6 0xbe89e64bb5a210bf      0t0  TCP [::1]:54006->[::1]:53856 (ESTABLISHED)
dart      98568 jdoe   11u  IPv6 0xbe89e64bb5a205ff      0t0  TCP [::1]:54007->[::1]:53856 (ESTABLISHED)
dart      98568 jdoe   12u  IPv6 0xbe89e64bb62505df      0t0  TCP [::1]:54075->[::1]:53856 (ESTABLISHED)
dart      98568 jdoe   13u  IPv6 0xbe89e64bb5a1fb3f      0t0  TCP [::1]:54008->[::1]:53856 (ESTABLISHED)
dart      98568 jdoe   14u  IPv6 0xbe89e64bb5a1f5df      0t0  TCP [::1]:54009->[::1]:53856 (ESTABLISHED)
...
``` 

Then, I did the most elite thing a programmer could do, in introducing a pause in the beginning of the for loop:

`await new Future.delayed(const Duration(milliseconds : 100));`

Result: script is running through without error.

So I am assuming "garbage collection" and closing those connections is not happening fast enough.
Would it be possible to introduce a `close()` method to the `Resource`class?

On a side note, but not able to reproduce: When introducing a delay of 50ms, the whole script freezes sometimes, at around 360 iterations.

**Comment by lrhn** [comment]
That is a lot of localhost connections.

I'll check if the `Resource`  is keeping any HTTP connections alive. It doesn't do it deliberately, but it might be a default I'm not aware of.

**Comment by lrhn** [comment]
Turns out that the `HttpClient` does have a 15 second keep-alive, but that's probably not the issue if a 100 ms delay is enough to make a difference.
More likely the problem is that you make 224+ concurrent connections that are all active at the same time. That does require 224 open file descriptors, and OSX has only 256 file descriptors per process as default.
I'll try setting `maxConnectionsPerHost` to six (like a browser) which will avoid more than that many concurrent connections to the *same* host. It might be enough to throttle your program. It'll probably also slow it down if it really wants to read all the files immediately.

**Comment by nilsdoehring** [comment]
Thanks so much for looking into it.

Regarding the 15 second keep-alive, it seems to be the issue: After 15 seconds (i.e. 150 connections), the first connections will get closed, thus the script will never reach the "256 limit".

I'll look into the effects of `maxConnectionsPerHost`. 
But: What do you think about introducing a `close()` method that invokes `HttpClient`'s close method?

Background: My use case is to get a large number of files and assets from a package's lib directory written into the directory from where the script of that package was called (via `pub global run ...`). It would be unfortunate if it took longer than the current workaround with 100ms delay.

**Comment by lrhn** [comment]
There is the option of not keeping alive (setting the `maxIdleTime` which defaults to 15 seconds), but that also comes with a performance cost if you do make lots of connections to the same host.

By setting the `maxConnectionsPerHost` to 6, I hope that multiple connections to the same host will be pipelined and then they will take advantage of the keep-alive connections in the connection pool.

The big problem here is that `Resource` is a black-box. There is no API to change the settings for the internal `HttpRequest` because that assumes a specific implementation of the HTTP protocol (dart:io vs. dart:html).

I have published a new version of package:resource, you can try that and see if it helps
We could lower the maxIdleTime, but that's somewhat arbitrary (lower it just enough, and tomorrow you get a faster computer and hit the problem again). The real problem is that you are trying to make more connections at a time than what your OS supports, and Dart can't save you from that. That's between your program and your OS. If it's just yourself having the problem, raising the default number of file descriptors per process might be the simplest solution.

**Comment by nilsdoehring** [comment]
Thank you for explaining the `Resource`black box. No `close()`possible, understood.
Just tested the new version v2.1.1: The error doesn't happen anymore at file number 224, but at file number 310.

About my 'real problem': Point taken, but I'm trying exactly what you explained – prevent my program from making more connections than the underlying OS supports. See the example below. With `Resource` being a black box, I am out of options besides using the dirty 'delay hack'?

```dart
// This will fail in OSX
Future myMethod() async {
  Resource r;
  for(int i=0; i<500;i++) {
    /* await new Future.delayed(const Duration(milliseconds : 100)); */
    r = new Resource(''package:foo/resource_${i}.bar");
    List<int> bytes = await r.readBytes();
    // r.close() would be nice
    /* do something */
  }
}
```

By the way, my use case is the same one as [stagehand](https://github.com/google/stagehand)'s, which is used in IntelliJ Dart plugin to auto-generate project skeletons. In stagehand, all assets need to be encoded by script into byte arrays before submitting the package to pub. I was (and still am) hoping to be able to replace that behavior by using `Resource`. I still have to run a script that generates an array of the resource uri's, but it's significantly smaller (like 5000%) than doing it the old way.

**Comment by lrhn** [comment]
Ok, you really are loading a lot of files from *different* servers at the same time, so we need to throttle somehow.
The resource package doesn't know what limits your current computer has, so perhaps it's better if you make the constraints, rather than baking them in. (The alternative opinion is that nobody can predict this, so we should always throttle to something "reasonable", but it's hard to predict what is reasonable since it depends on what your process is otherwise doing).

One solution is to have a throttling loader. Maybe something like the following (not tested!)
```dart
import "dart:async";
import "dart:collection";
import "dart:convert";
import "package:async/async.dart"
    show StreamCompleter, DelegatingStreamSubscription;
import "package:resource/resource.dart" show ResourceLoader;

class ThrottleLoader implements ResourceLoader {
  ResourceLoader _loader;
  int _capacity;
  final _backlog = new Queue<Function>();
  ThrottleLoader(int capacity, {ResourceLoader loader})
      : _capacity = capacity, _loader = loader ?? ResourceLoader.defaultLoader;
  void _complete() {
    if (_backlog.isEmpty) {
      _capacity++;
    } else {
      _backlog.removeFirst()();
    }
  }
  Future<String> readAsString(Uri uri, {Encoding encoding}) {
    if (_capacity > 0) {
      _capacity--;
      return _loader.readAsString(uri, encoding: encoding)
                    .whenComplete(_complete);
    }
    var completer = new Completer<String>();
    _backlog.add(() {
      completer.complete(_loader.readAsString(uri, encoding: encoding));
    });
    return completer.future;
  }
  Future<List<int>> readAsBytes(Uri uri) {
    if (_capacity > 0) {
      _capacity--;
      return _loader.readAsBytes(uri).whenComplete(_complete);
    }
    var completer = new Completer<List<int>>();
    _backlog.add(() {
      completer.complete(_loader.readAsBytes(uri));
    });
    return completer.future;
  }
  Stream<List<int>> openRead(Uri uri) {
    if (_capacity > 0) {
      _capacity--;
      return new _CompleterStream(_loader.openRead(uri), this);
    }
    var completer = new StreamCompleter<List<int>>();
    _backlog.add(() {
      completer.setSourceStream(_loader.openRead(uri));
    });
    return new _CompleterStream(completer.stream, this);
  }
}
class _CompleterStream extends Stream<List<int>> {
  final Stream<List<int>> _source;
  ThrottleLoader  _loader;
  _CompleterStream(this._source, this._loader);
  StreamSubscription<List<int>> listen(void onData(List<int> data), {
    Function onError, void onDone(), bool cancelOnError : false}) {
    return new _CompleterSubscription(
        _source.listen(onData, cancelOnError: cancelOnError),
                      cancelOnError, _loader)
      ..onError(onError)
      ..onDone(onDone);
  }
}
typedef _Binary(a, b);
class _CompleterSubscription extends DelegatingStreamSubscription<List<int>> {
  final bool _cancelOnError;
  final ThrottleLoader _loader;
  _CompleterSubscription(
      StreamSubscription<List<int>> sub, this._cancelOnError, this._loader)
      : super(sub);
  onDone(void doneHandler()) {
    super.onDone(() {
      _loader._complete();
      if (doneHandler != null) super.onDone(doneHandler);
    });
  }
  onError(Function errorHandler) {
    if (!_cancelOnError) {
      super.onError(errorHandler);
      return;
    }
    if (errorHandler is _Binary) {
      super.onError((e, s) {
        _loader._complete();
        errorHandler(e, s);
      });
    } else {
      super.onError((e) {
        _loader._complete();
        if (errorHandler != null) errorHandler(e);
      });
    }
  }
  Future cancel() {
    return super.cancel().whenComplete(_loader._complete);
  }
}
```

With that, you can do:
```dart
var throttle = new ThrottleLoader(120);
...
new Resource("some uri", loader: throttle).readAsString();
...
```
and you won't get more than 120 concurrent requests.

**Comment by nilsdoehring** [comment]
@lrhn thanks so much for this elaborate example, works like a charm!
