### ISSUE TITLE
Resource.readAsString is doing something wrong with encoding.

### ISSUE THREAD

**Issue by eseidel** [dart-lang/resource#21]
I suspect this may be a combination of the webserver doing something strange and Resource being strange, but I lost a couple hours tracking this down this afternoon. :/

package:http reads the json file no problem, package:resource encodes it wrong somehow.

This is likely the problem code:
https://github.com/dart-lang/resource/blob/master/lib/src/io_io.dart#L64

Repro:
```
import 'package:http/http.dart' as http;
import 'package:resource/resource.dart';

void main() async {
  String url =
      'http://ddragon.leagueoflegends.com/cdn/7.2.1/data/en_US/champion.json';
  String fromHttp = await http.read(url);
  String fromResource = await new Resource(url).readAsString();
  print('${fromHttp.length} ${fromResource.length}');
}
```
Output:
```
127543 255086
```

JSON.decode, etc. fails for package:resource, but succeeds in the package:http case.  Presumably package:resource should just use package:http instead of rolling its own?

**Comment by lrhn** [comment]
Those numbers do look suspiciously like they differ by a factor of 2. 
The simplest explanation is that the content is being sent as UTF-16, and the resource package doesn't recognize that. Another option is that the request isn't asking for the correct encoding. 

Package resource is rolling its own HTTP here. Using `package:http` is an option. Currently the `resource` package is using the experimental configurable imports, and the `http` package isn't.
