### ISSUE TITLE
Severe log using webdev build with dart 2.0.0-dev.58.0 for resource: "^2.1.4"

### ISSUE THREAD

**Issue by jox81** [dart-lang/resource#30]
Hello, 
I'm trying to build a project for use with dart 2.0.0-dev.58.0 on windows 10 but I've got the follawing errors :

environment:
  sdk: '>=2.0.0-dev.58.0 <2.0.0'
dependencies:
  resource: "^2.1.4"

webdev build --no-release --output web:build

[INFO] Building new asset graph completed, took 792ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] build_web_compilers|ddc on package:resource/resource.module:
Error compiling dartdevc module:resource|lib/resource.ddc.js

[error] Target of URI doesn't exist: 'io_html.dart'. (package:resource/src/resource_loader.dart, line 9, col 28)
[error] Target of URI doesn't exist: 'io_io.dart'. (package:resource/src/resource_loader.dart, line 10, col 26)

Please fix all errors before compiling (warnings are okay).
}
[WARNING] build_web_compilers|entrypoint on web/webgl/projects/test_load_assets_files/main.dart:
Unable to read resource|lib/resource.ddc.js, check your console or the `.dart_tool/build/generated/resource/lib/resource.ddc.js.errors` log file.
[INFO] Running build completed, took 15.2s
[INFO] Caching finalized dependency graph completed, took 298ms
[SEVERE] Failed after 15.7s

What's the point ?

Thank you

**Comment by lrhn** [comment]
As the linked pub issue states, this is an issue with DDC, not with this package.
