### ISSUE TITLE
Example in readme?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/resource#5]
Thanks for publishing! What do we think about adding an example to the readme? How do I use this? Does it work everywhere? What URI schemes are supported? (e.g., is package: supported?)

**Comment by mit-mit** [comment]
Yes, we should put a sample in the readme!

**Comment by lrhn** [comment]
There is now an example in a readme.

**Comment by lrhn** [comment]
Well, it's in the library documentation, not the readme. Reopen if you want it more places.

**Comment by sethladd** [comment]
Would be helpful to see it in the README, too. That way, when people find the github page or the pub.dartlang.org page, they will get a sense of what this does and how to use it. Thanks!

**Comment by sethladd** [comment]
Sending over a pull request

**Comment by lrhn** [comment]
And he landed it!
