### ISSUE TITLE
upgrade constraints on package_config

### ISSUE THREAD

**Issue by keertip** [dart-lang/resource#6]
Would like to use the resource package with dartdoc, but the current package_config version does not make it compatible. Please upgrade to ^0.1.1 (based on analyzer)

**Comment by lrhn** [comment]
I'm not sure the dependency is used any more. Maybe it can just be removed entirely.

**Comment by keertip** [comment]
removed package_config dependency as it was not in use.

**Comment by lrhn** [comment]
... and it's gone.
