### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/resource#8]
The 1.0.0 release doesn't seem to include support for browsers.
The following code clearly states that configuration dependent import is to be leveraged, and to my understanding, it won't be landing until 1.15:

https://github.com/dart-lang/resource/blob/master/lib/src/loader.dart#L8

So please clearly document that browser support is not in 1.0.0. Sharing of the future roadmap (even tentative) in that regard would be appreciated.

**Comment by lrhn** [comment]
That is correct. I was considering using the http package, but decided to wait for configurable imports instead.

I'll consider adding a browser version as well, which will, for now, require a separate import.

**Comment by dynaxis** [comment]
https://github.com/dart-lang/sdk/issues/25594
Is it an intended consequence? dart2js' `Isolate` doesn't seem to resolve `package:` uris.

**Comment by lrhn** [comment]
The `browser_resource.dart` library should work in the browser.
We'll have to keep the code depending on dart:html separate from the code depending on dart:io until we get a way to do conditional imports, so this is the best we can do.

(And yes, dart2js needs an update too).
