### ISSUE TITLE
Update changelog for 1.0.1 ?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/resource#9]
What's new in 1.0.1 ?

**Comment by sethladd** [comment]
cc @mit-mit @lrhn

**Comment by lrhn** [comment]
Only documentation updates
.
I don't think you need changelog entries for minor-version increments - they should, by definition, not be changing anything visible.

**Comment by sethladd** [comment]
If it only takes a moment, please consider updating the CHANGELOG for every release. It avoids the "what am I missing? what's new?" question and uncertainty from users. Even a "updated API docs" is a useful note. Thanks!
